name: riverpod_repo
description: A Lib to build Riverpod providers based on the reposirory interfaces.
version: 5.0.0
homepage: https://dilan.me
repository: https://github.com/chaturadilan/riverpod_repo_generator

environment:
  sdk: ^3.10.8
  flutter: ">=3.35.0"

topics:
  - riverpod
  - code-generation
  - repository-pattern
  - flutter
  - dart

dependencies:
  flutter:
    sdk: flutter
  build: ^4.0.6
  source_gen: ^4.2.3
  recase: ^4.1.0
  analyzer: ">=9.0.0 <14.0.0"
  riverpod: ^3.2.1
  riverpod_annotation: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.15.0
  riverpod_generator: ^4.0.3

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
